/**
 * Serves the main Single Page Application.
 */
function doGet() {
  return HtmlService.createHtmlOutputFromFile('Index')
    .setTitle('HR Analytics AI Hub')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)
    .addMetaTag('viewport', 'width=device-width, initial-scale=1');
}

/**
 * securely fetches the Gemini API key from Script Properties.
 * Run `setApiKey` ONCE from the Apps Script editor to save your key.
 */
function setApiKey() {
  // Uncomment and run this ONCE in the browser editor, then delete it.
  // PropertiesService.getScriptProperties().setProperty('GEMINI_API_KEY', 'YOUR_ACTUAL_KEY_HERE');
}

/**
 * Handles communication between the frontend client and the Gemini API.
 * @param {string} userMessage - The query from the user.
 * @param {string} dataSummary - The aggregated data context generated by the frontend.
 * @returns {string} Markdown formatted response from AI.
 */
function askChatbot(userMessage, dataSummary) {
  const apiKey = PropertiesService.getScriptProperties().getProperty('GEMINI_API_KEY');
  
  if (!apiKey) {
    return "❌ **System Error:** API Key not configured. Please contact the administrator.";
  }

  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;
  
  const prompt = `You are a Senior HR Data Analytics AI. 
  Analyze the following aggregated HR data from the user's current session:
  
  --- DATA SUMMARY ---
  ${dataSummary}
  --------------------
  
  User Query: "${userMessage}"
  
  Instructions:
  1. Provide accurate insights based ONLY on the provided summary.
  2. Format your response using Markdown. Use tables for breakdowns and bold text for key numbers.
  3. Keep the tone professional, analytical, and objective.`;

  const payload = {
    "contents": [{"parts": [{"text": prompt}]}],
    "generationConfig": { "temperature": 0.1 } // Strict analytical temperature
  };

  const options = {
    "method": "post",
    "contentType": "application/json",
    "payload": JSON.stringify(payload),
    "muteHttpExceptions": true
  };

  try {
    const response = UrlFetchApp.fetch(url, options);
    const json = JSON.parse(response.getContentText());
    
    if (json.error) {
       console.error("API Error:", json.error.message);
       return `❌ **API Error:** ${json.error.message}`;
    }
    
    if(json.candidates && json.candidates.length > 0) {
       return json.candidates[0].content.parts[0].text;
    }
    return "⚠️ I couldn't process that response. Check the data format.";
  } catch (e) {
    console.error("Execution Error:", e);
    return `❌ **Server Error:** ${e.message}`;
  }
}
